### PR TITLE
Add assertions for ClientIP, Url and ProxyUrl

### PR DESCRIPTION
**Pull request by akamud**

### CODE REVIEW

**Review by StefH — CHANGES_REQUESTED** [review]
1. Can you merge latest master into your branch? There is a problem with sonar scanner

2. Can you put `params object[] becauseArgs` on the same line as the method?

**Review by musthafam — APPROVED** [review]

**Comment by akamud** [comment]
Hi, don't worry, I will make these changes as soon as I get time this week.

**Comment by akamud** [comment]
Pushed all the requested changes.

**Review by StefH — APPROVED** [review]

**Comment by StefH** [comment]
@akamud --> Thanks!

**Pull request merged**
