### PR TITLE
Made changes to accommodate breaking change in testcontainers-dotnet 3.9

### PR DESCRIPTION
**Pull request by epDugas**
Made changes to accommodate breaking change in testcontainers-dotnet 3.9

[3.9.0](https://github.com/testcontainers/testcontainers-dotnet/releases/tag/3.9.0)
[1146](https://github.com/testcontainers/testcontainers-dotnet/pull/1146)
[1100](https://github.com/testcontainers/testcontainers-dotnet/pull/1100)

### CODE REVIEW

**Comment by StefH** [comment]
> Made changes to accommodate breaking change in testcontainers-dotnet 3.9
> 
> Ref: [testcontainers/testcontainers-dotnet#1100](https://github.com/testcontainers/testcontainers-dotnet/pull/1100)

Is this for sure a breaking change?

**Comment by epDugas** [comment]
> > Made changes to accommodate breaking change in testcontainers-dotnet 3.9
> > Ref: [testcontainers/testcontainers-dotnet#1100](https://github.com/testcontainers/testcontainers-dotnet/pull/1100)
> 
> Is this for sure a breaking change?

Yes, added relevant urls to pr description.

**Comment by StefH** [comment]
Ok. Thanks for the heads-up.

This is not the first time they introduce a breaking change in a minor version.

Is there a better way to handle this? Or is it only feasible to fix it like this PR?

**Comment by epDugas** [comment]
> Ok. Thanks for the heads-up.
> 
> This is not the first time they introduce a breaking change in a minor version.
> 
> Is there a better way to handle this? Or is it only feasible to fix it like this PR?

Yeah, I saw the reason you had to pin to 3.7. 
There may be a better way, but I didn't see an obvious one. I just made the change match the changes that were made to all of the included ContainerBuilders.

**Pull request merged**
