### PR TITLE
Bring in the WireMock.Net.FluentAssertions tests

### PR DESCRIPTION
**Pull request by akamud**
Porting over the tests from the original project.

### CODE REVIEW

**Comment by StefH** [comment]
Maybe put the tests into separate test files? Based on the name from the class?

**Comment by akamud** [comment]
Can you elaborate more, please? I'm only testing the `WireMockAssertions` at the moment, so it is in the `WireMockAssertionsTests`, but since it depends on the other classes, they are covered as part of the integrated tests I wrote.

Do you mean writing separate test for the supporting classes? (WireMockReceivedAssertions, WireMockANumberOfCallsAssertions, etc.?)

**Comment by StefH** [comment]
Correct.
Unless it does not make sense?

**Comment by akamud** [comment]
I think they are very simple at the moment and writing extra unit tests for them doesn't bring much value, since their behavior are guaranteed by the Assertions tests and can't be mocked at the moment.
The only part I'm not testing yet, is the `Received(int numberOfCalls)`, but that's because I'm not using it either. They were more like a draft for the future, since I wasn't planning on writing the scenarios for asserting exactly the number of times for now.

Given that, would you like me to change anything?

**Comment by StefH** [comment]
I will check tomorrow.

**Pull request merged**
