### PR TITLE
Provide open api schema to dynamic examples generator so you can generate accurate data

### PR DESCRIPTION
**Pull request by brunotarghetta**
@StefH  Having ope api Schema we can use settings like max-length in case of a string to generate more accurate mock data when you implement your dynamic examples

### CODE REVIEW

**Review by StefH — CHANGES_REQUESTED** [review]
See my comments.

And I wonder how to can be used, can you add an example (maybe in the https://github.com/WireMock-Net/WireMock.Net/tree/master/examples/WireMock.Net.OpenApiParser.ConsoleApp ?)

**Comment by brunotarghetta** [comment]
@StefH I've made the changes you suggested. Also I added some code on the ConsoleApp to show you how this can be useful.
Let me share some images

In you swagger file you can specify some attributes (maxLength on string types)
Screen Shot 2021-12-27 at 14 21 46

Screen Shot 2021-12-27 at 14 21 24

So, if you are working with your own example values generator, you can use this settings

Screen Shot 2021-12-27 at 14 41 43

as a result you can check on mapping those examples string with their own length


Screen Shot 2021-12-27 at 14 36 26

In our case this is really useful

Let me know if you need more information.

Thanks in advance.

**Review by StefH — CHANGES_REQUESTED** [review]
Looks good.

Can you do these 2 changes:

Add `virtual` to all public methods in:
- `WireMockOpenApiParserExampleValues.cs`
- `WireMockOpenApiParserDynamicExampleValues.cs`

With that change, you can just easily extend from the existing class and override the existing methods. (Can be useful for your new file "DynamicDataGeneration.cs").

**Comment by brunotarghetta** [comment]
@StefH I've made virtual changes and I extend my DynamicDataGeneration.

**Review by StefH — APPROVED** [review]

**Comment by brunotarghetta** [comment]
Hi @StefH, good morning! do you know when this features will be release?

**Comment by StefH** [comment]
@brunotarghetta 

New NuGet packages will be released in a few minutes...

**Comment by brunotarghetta** [comment]
> @brunotarghetta
> 
> New NuGet packages will be released in a few minutes...

That sound great!!!!!!! Thanks!!

**Pull request merged**
