### PR TITLE
[265] Add file upload to allow mocking of file operations

### PR DESCRIPTION
**Pull request by JackCreativeCrew**
I've added endpoints for file upload/download/deletion (PUT/GET/DELETE) to allow for testing using files. The code is pretty basic but fulfills my requirements at the moment and has test coverage of happy paths.

### CODE REVIEW

**Comment by StefH** [comment]
Thanks for this idea + implementation.

I'll refactor the code in this branch to match the solution logic.

**Comment by StefH** [comment]
@JackCreativeCrew 
I did update the code, and also added a `PostFile`.

Can you check the latest version on MyGet: https://www.myget.org/feed/wiremock-net/package/nuget/WireMock.Net ?

**Comment by JackCreativeCrew** [comment]
Minor change to create the __admin/mapping folder if it doesn't exist otherwise the file upload fails. I'd imagine this is a problem in other places too (scenarios etc)?

**Comment by StefH** [comment]
Actually I was just thinking about that scenario.

Also your remark bout returning the path.
--> this does not make sense because I think I will only allow writing files in the __admin/mapping and no not allow sub-folders.
Because withe current code you can use:
`POST http://{{wm_hostname}}/__admin/files/x/1.cs` which will try to save the file in the __admin/mapping/x folder.
And this fails because the "x" folder does not exists.

And actually, I think this is also a security risk to allow sub-folders or different paths like `/../../system32.dll` (as an example...)

So I think I will add logic to the code to take the filename only and change _path_ into _filename_ in the interface

**Comment by JackCreativeCrew** [comment]
Yeah, ok, I hadn't considered that.

Something else I've come across, the file is being written as everything in the multipart body which isn't just the file. I've stuffed around trying to get this to write just the file but as yet failed.
I get for instance 
```
----------------------------566196384670995956765212
Content-Disposition: form-data; name=""; filename="pdf_viewer_resources.pak"
Content-Type: application/octet-stream

```
at the head and 
```

----------------------------566196384670995956765212--

```
at the tail. At the moment I'm only using one file i.e. that file, is there any way to only write the first piece of content and just chop the rest?

**Comment by StefH** [comment]
First I will fix the unit-tests
Second I will think about multipart...

**Comment by StefH** [comment]
**Second**
When I just upload a single file using Postman, only the file-content is uploaded, nothing to see as multipart...

**Comment by JackCreativeCrew** [comment]
I must be doing something wrong on my end then. Thanks for checking that out.

**Comment by StefH** [comment]
If you have tested all scenarios in this branch, and are confident that this code is correct, I can merge this PR and create a new NuGet.

**Comment by JackCreativeCrew** [comment]
> If you have tested all scenarios in this branch, and are confident that this code is correct, I can merge this PR and create a new NuGet.

I haven't had time today to review/check my stuff against this today sorry. I'll get back to you by the end of tomorrow Sydney time though.

**Comment by JackCreativeCrew** [comment]
Ok I've added a HEAD endpoint as well and a test for both file found and not found. It requires no body as the HEAD request can't have a body so the structure is a bit different. The code is now all working for me and if you accept those changes, I'm ok with merging it.

**Comment by StefH** [comment]
Head is a good idea.

I did some small updates on code + tests, and I added this call also to the `IFluentMockServerAdmin.cs`

**Comment by JackCreativeCrew** [comment]
Yeah, I was using that for debugging which admin endpoints were available, must've not gotten deleted before the commit.

**Comment by StefH** [comment]
I'll merge to master now.

**Pull request merged**
